import Footer from "../components/Footer";
// import HeaderTop from "../components/HeaderTop";
// import Navbar from "../components/Navbar";
// import { SearchInput } from "../components/SearchInput";
import FullHeader from "../components/FullHeader";
import SearviceBanner from "../components/SearviceBanner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <FullHeader />
      <hr />
      <br />
      {/* <Navbar /> */}
      {children}
      <SearviceBanner />
      <Footer />
    </>
  );
}
