import Footer from "@/src/app/[locale]/components/Footer";
import FullHeader from "@/src/app/[locale]/components/FullHeader";
import SearviceBanner from "@/src/app/[locale]/components/SearviceBanner";

export const metadata = {
  title: "Perfume",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <FullHeader />
      <hr />
      <br />
      {children}
      <SearviceBanner />
      <Footer />
    </>
  );
}
