import Footer from "@/src/app/[locale]/components/Footer";
// import HeaderTop from "../components/HeaderTop";
// import Navbar from "../components/Navbar";
// import { SearchInput } from "../components/SearchInput";
import FullHeader from "@/src/app/[locale]/components/FullHeader";
import SearviceBanner from "@/src/app/[locale]/components/SearviceBanner";

export const metadata = {
  title: "Men",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      {/* <HeaderTop />
      <SearchInput /> */}
        <FullHeader />
      <hr />
      <br />
      {/* <Navbar /> */}
      {children}
      <SearviceBanner />
      <Footer />
    </>
  );
}
