import HeaderTop from "../components/HeaderTop";
import { SearchInput } from "../components/SearchInput";
import Navbar from "../components/Navbar";
import SearviceBanner from "../components/SearviceBanner";
import Footer from "../components/Footer";

export const metadata = {
  title: "About",
  description: "Generated by Next.js",
};

// habe HTML UND BODY tags geloscht | have deleted HTML AND BODY tags and in all other sub-layouts

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <HeaderTop />
      <SearchInput />
      <hr />
      <br />
      <Navbar />
      {children}
      <SearviceBanner />
      <Footer />
    </>
  );
}
