import Footer from "../components/Footer";
import FullHeader from "../components/FullHeader";
import SearviceBanner from "../components/SearviceBanner";

export const metadata = {
  title: "Sign up",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        <FullHeader />
      <hr />
      <br />
      {children}
      <SearviceBanner />
      <Footer />
    </>
  );
}
